### ISSUE TITLE
双链效果更改待讨论（原：双链的颜色希望改的明显一些）

### ISSUE THREAD

**Issue by vipyanzg** [Oltermare/Consistent#1]
在明亮模式下，双链的颜色不是很明显

**Comment by Oltermare** [comment]
你好，这个主题的特点就是弱化链接对阅读的影响，所以暂时不会更改，如果觉得双链的效果还需要更改的朋友，可以再继续讨论。

如果你需要增强双链的效果，可以打开设置-外观-代码片段，把以下代码复制过去并开启，更换为原来的更明亮的蓝色

```
.protyle-wysiwyg [data-node-id] span[data-type~=block-ref], .protyle-wysiwyg [data-node-id] span[data-type~=file-annotation-ref] {
    color: var(--b3-protyle-inline-link-color) !important;
}
.protyle-wysiwyg[contenteditable=true] span[data-type~=block-ref]:hover, .protyle-wysiwyg[contenteditable=true] span[data-type~=file-annotation-ref]:hover {
    border-bottom: solid 1px var(--b3-protyle-inline-link-color) ;
}
```

![image](https://user-images.githubusercontent.com/64324088/199788212-d8d78e29-df46-4276-9900-9a59a6432bcb.png)

**Comment by Oltermare** [comment]
最近使用感觉有实话需要用星号*来引用，在这种很少字符的情况下，现在的样式确实不明显，但是不想改配色，也不想在前后加中括号，应该会增加一个淡颜色背景，可能会考虑渐变

> 在明亮模式下，双链的颜色不是很明显

**Comment by Oltermare** [comment]
> 最近使用感觉有实话需要用星号*来引用，在这种很少字符的情况下，现在的样式确实不明显，但是不想改配色，也不想在前后加中括号，应该会增加一个淡颜色背景，可能会考虑渐变
> 
> > 在明亮模式下，双链的颜色不是很明显

等这个版本上完集市，再更新一下

**Comment by Oltermare** [comment]
已经把所有连接的蓝色改成更鲜艳一点的蓝色，标签前后增加间隔，1.0.5更新
